/* ═══════════════════════════════════════════════════════════════
   COLDBASE · Diligencias
   102 plantillas de consulta instanciadas sobre los 7 expedientes
   = 714 diligencias. Cada una se valida comparando el resultado
   de la consulta del analista con el de la consulta de referencia.
   ═══════════════════════════════════════════════════════════════ */
var CDB = window.CDB || {};
window.CDB = CDB;

(function(){
"use strict";

CDB.BLOQUES=[
{n:"ACTA DE RECONOCIMIENTO",corto:"ACTA",
 d:"Antes de acusar a nadie hay que saber que hay en la caja. Aqui aprendes a pedirle al sistema lo que guarda sobre este expediente: columnas, filas y nada mas."},
{n:"CRIBA DE SOSPECHOSOS",corto:"CRIBA",
 d:"Un expediente frio tiene demasiados nombres. Filtrar es el oficio: quedarte solo con las filas que todavia pueden sostener una acusacion."},
{n:"ORDEN DE DILIGENCIAS",corto:"ORDEN",
 d:"El orden cuenta una historia. Ordenando llamadas por hora o testigos por fiabilidad aparece la secuencia que el instructor nunca vio."},
{n:"CRUCE DE EXPEDIENTES",corto:"CRUCE",
 d:"Las tablas sueltas no acusan a nadie. Uniendo personas con sospechosos, evidencias con laboratorios y casos con detectives, el archivo empieza a hablar."},
{n:"RECUENTO FORENSE",corto:"RECUENTO",
 d:"Cuantos, cuanto y desde cuando. Los agregados convierten cincuenta anos de papel en cifras que caben en un informe."},
{n:"INTERROGATORIO PROFUNDO",corto:"INTERROG",
 d:"Preguntas dentro de preguntas. Las subconsultas sirven para lo que ningun filtro simple alcanza: quien aparece donde no deberia."},
{n:"RECONSTRUCCION DEL CASO",corto:"RECONST",
 d:"La ultima diligencia es escribir. Con CASE, COALESCE y uniones montas el acta que devuelve el expediente a la vida."}
];

/* ─────────── Datos de apoyo por expediente ─────────── */
var EXTRA={
1:{sosp:"G. Petrakis",tes:"D. Hollis",ev:"EV-01",num:"213-555-0144",lab:"LAB-1 Criminalistica",pal:"silbido",dep:"DEP-CENTRAL",amb:"el sendero del observatorio"},
2:{sosp:"H. Brummel",tes:"M. Quigley",ev:"EV-02",num:"213-555-7710",lab:"LAB-1 Criminalistica",pal:"escalera",dep:"DEP-CENTRAL",amb:"las escaleras de Angels Flight"},
3:{sosp:"R. Kessler",tes:"A. Mori",ev:"EV-01",num:"213-555-0392",lab:"LAB-1 Criminalistica",pal:"emergencias",dep:"DEP-NORTE",amb:"el estanque de Echo Park"},
4:{sosp:"E. Thorne",tes:"F. Lindqvist",ev:"EV-01",num:"818-555-4001",lab:"LAB-2 Biologia Forense",pal:"ronda",dep:"DEP-NORTE",amb:"el mirador de Mulholland"},
5:{sosp:"J. Farrow",tes:"K. Ibarra",ev:"EV-01",num:"323-555-8812",lab:"LAB-3 Toxicologia",pal:"estudio",dep:"DEP-SUR",amb:"el estudio de Silver Lake"},
6:{sosp:"C. Mellado",tes:"G. Varela",ev:"EV-02",num:"213-555-0392",lab:"LAB-2 Biologia Forense",pal:"fichaje",dep:"DEP-PUERTO",amb:"la caseta del muelle 9"},
7:{sosp:"E. Thorne",tes:"P. Ferreiro",ev:"EV-01",num:"818-555-4001",lab:"LAB-4 Incendios",pal:"alarma",dep:"DEP-NORTE",amb:"la nave de Verdugo"}
};

/* ─────────── Plantillas ─────────── */
/* g: bloque · b(c): enunciado · h: pista · o: hallazgo · s(c): consulta de
   referencia · re: fragmento obligatorio en la consulta del analista      */
var TPL=[

/* ════ 0 · ACTA DE RECONOCIMIENTO ════ */
{g:0,b:c=>`Abre la ficha completa del expediente ${c.cod} con todas sus columnas.`,
 h:"SELECT * FROM casos WHERE caso_id = <id>",
 o:"Ficha en pantalla. Ese codigo va a encabezar todo lo que escribas esta noche.",
 s:c=>`SELECT * FROM casos WHERE caso_id = ${c.id}`},
{g:0,b:c=>`Del expediente ${c.cod}, pide solo el codigo, el titulo y el ano.`,
 h:"Nombra las columnas separadas por comas en lugar del asterisco.",
 o:"Tres columnas, cero ruido. Asi se cita un caso en un informe.",
 s:c=>`SELECT codigo, titulo, anio FROM casos WHERE caso_id = ${c.id}`},
{g:0,b:c=>`Saca la ficha completa de la victima de este expediente.`,
 h:"La tabla es victimas y se filtra por caso_id.",
 o:c=>`${c.vict}. A partir de aqui ya no es una fila, es una persona.`,
 s:c=>`SELECT * FROM victimas WHERE caso_id = ${c.id}`},
{g:0,b:c=>`De la victima, pide unicamente su nombre y su edad.`,
 h:"SELECT nombre, edad FROM victimas ...",
 o:"Dos datos que caben en un titular y resumen una vida entera.",
 s:c=>`SELECT nombre, edad FROM victimas WHERE caso_id = ${c.id}`},
{g:0,b:c=>`Repite la consulta anterior pero renombrando las columnas: el nombre como victima y la causa de muerte como causa.`,
 h:"Usa AS para poner alias a cada columna.",o:"Columnas con el nombre que tu decides. El informe empieza a tener forma.",
 re:"\\bas\\b",s:c=>`SELECT nombre AS victima, causa_muerte AS causa FROM victimas WHERE caso_id = ${c.id}`},
{g:0,b:c=>`Lista todos los sospechosos registrados en ${c.cod}.`,
 h:"SELECT * FROM sospechosos WHERE caso_id = <id>",
 o:"Ahi estan todos, con coartada o sin ella.",
 s:c=>`SELECT * FROM sospechosos WHERE caso_id = ${c.id}`},
{g:0,b:c=>`Lista todos los testigos del expediente.`,h:"La tabla es testigos.",
 o:"Gente que vio algo y a la que nadie volvio a llamar.",
 s:c=>`SELECT * FROM testigos WHERE caso_id = ${c.id}`},
{g:0,b:c=>`Lista todas las evidencias recogidas en ${c.amb}.`,h:"La tabla es evidencias.",
 o:"Tres bolsas selladas que llevan decadas esperando.",
 s:c=>`SELECT * FROM evidencias WHERE caso_id = ${c.id}`},
{g:0,b:c=>`De esas evidencias, pide solo el codigo y la descripcion.`,
 h:"SELECT codigo, descripcion FROM evidencias ...",o:"El inventario limpio, listo para pegarlo en el acta.",
 s:c=>`SELECT codigo, descripcion FROM evidencias WHERE caso_id = ${c.id}`},
{g:0,b:c=>`Saca el registro telefonico completo de la noche del hecho.`,h:"La tabla es llamadas.",
 o:"La noche entera en cuatro lineas de telefono.",
 s:c=>`SELECT * FROM llamadas WHERE caso_id = ${c.id}`},
{g:0,b:c=>`Averigua que sentidos de llamada aparecen en este expediente, sin repetir ninguno.`,
 h:"DISTINCT elimina los valores repetidos.",o:"Entrantes y salientes. Nada mas, pero importa cual fue la ultima.",
 re:"distinct",s:c=>`SELECT DISTINCT sentido FROM llamadas WHERE caso_id = ${c.id}`},
{g:0,b:c=>`Lista los estados de coartada distintos que se registraron en ${c.cod}.`,
 h:"SELECT DISTINCT estado_coartada FROM sospechosos ...",
 o:"El abanico completo de excusas de este expediente.",
 re:"distinct",s:c=>`SELECT DISTINCT estado_coartada FROM sospechosos WHERE caso_id = ${c.id}`},
{g:0,b:c=>`Trae solo las tres primeras declaraciones del expediente.`,
 h:"LIMIT corta el resultado a un numero de filas.",o:"Tres declaraciones. Suficiente para empezar a dudar.",
 re:"limit",s:c=>`SELECT * FROM declaraciones WHERE caso_id = ${c.id} LIMIT 3`},
{g:0,b:c=>`Lista los informes que se firmaron sobre este caso.`,h:"La tabla es informes.",
 o:"Pocos informes y muchos anos entre uno y otro.",
 s:c=>`SELECT * FROM informes WHERE caso_id = ${c.id}`},

/* ════ 1 · CRIBA DE SOSPECHOSOS ════ */
{g:1,b:c=>`Quedate solo con los sospechosos de ${c.cod} cuya coartada no esta confirmada.`,
 h:"Usa <> para decir distinto de.",o:"Esos son los que siguen vivos como linea de investigacion.",
 s:c=>`SELECT * FROM sospechosos WHERE caso_id = ${c.id} AND estado_coartada <> 'CONFIRMADA'`},
{g:1,b:c=>`Lista los sospechosos del expediente que la unidad nunca descarto.`,
 h:"La columna descartado es booleana: compara con false.",o:"La lista corta. La que de verdad importa.",
 s:c=>`SELECT * FROM sospechosos WHERE caso_id = ${c.id} AND descartado = false`},
{g:1,b:c=>`Filtra los sospechosos cuya coartada quedo como SIN DECLARAR o NO VERIFICABLE, usando una lista de valores.`,
 h:"IN ('A','B') evita encadenar varios OR.",o:"Dos estados, una sola condicion. El filtro ya parece de perito.",
 re:"\\bin\\b",s:c=>`SELECT * FROM sospechosos WHERE caso_id = ${c.id} AND estado_coartada IN ('SIN DECLARAR','NO VERIFICABLE')`},
{g:1,b:c=>`Saca las llamadas de esa noche que duraron mas de un minuto.`,
 h:"La duracion esta en segundos: duracion_seg > 60",o:"Las llamadas largas son conversaciones, no avisos.",
 s:c=>`SELECT * FROM llamadas WHERE caso_id = ${c.id} AND duracion_seg > 60`},
{g:1,b:c=>`Ahora quedate solo con las llamadas entrantes del expediente.`,
 h:"sentido = 'ENTRANTE'",o:"Alguien le llamaba. Falta saber quien.",
 s:c=>`SELECT * FROM llamadas WHERE caso_id = ${c.id} AND sentido = 'ENTRANTE'`},
{g:1,b:c=>`Busca las llamadas cortisimas, de menos de 200 segundos, usando un rango.`,
 h:"BETWEEN 1 AND 200 define el intervalo de duracion.",o:"Llamadas de pocos segundos: comprobaciones, no conversaciones.",
 re:"between",s:c=>`SELECT * FROM llamadas WHERE caso_id = ${c.id} AND duracion_seg BETWEEN 1 AND 200`},
{g:1,b:c=>`Localiza las llamadas cuyo numero contiene 555, buscando por patron.`,
 h:"LIKE '%555%' busca ese fragmento en cualquier posicion.",o:"Numeros reales frente a lineas sin identificar.",
 re:"like",s:c=>`SELECT * FROM llamadas WHERE caso_id = ${c.id} AND numero LIKE '%555%'`},
{g:1,b:c=>`Quedate con los testigos de fiabilidad alta, de 4 para arriba.`,
 h:"fiabilidad >= 4",o:"Los testigos que un fiscal aceptaria sin pestanear.",
 s:c=>`SELECT * FROM testigos WHERE caso_id = ${c.id} AND fiabilidad >= 4`},
{g:1,b:c=>`Busca las declaraciones de este expediente que nunca llegaron a firmarse.`,
 h:"firmada = false",o:"Papeles sin firma. En un juicio no valen nada.",
 s:c=>`SELECT * FROM declaraciones WHERE caso_id = ${c.id} AND firmada = false`},
{g:1,b:c=>`Busca en el texto de las declaraciones la palabra "${EXTRA_pal(c)}", sin que importen las mayusculas.`,
 h:"ILIKE hace la busqueda sin distinguir mayusculas.",o:"Una palabra en un parrafo, y de pronto el expediente tiene un hilo.",
 re:"ilike",s:c=>`SELECT * FROM declaraciones WHERE caso_id = ${c.id} AND contenido ILIKE '%${EXTRA_pal(c)}%'`},
{g:1,b:c=>`Lista las evidencias de este caso que siguen selladas.`,
 h:"estado = 'SELLADA'",o:"Lo que todavia se puede analizar hoy mismo.",
 s:c=>`SELECT * FROM evidencias WHERE caso_id = ${c.id} AND estado = 'SELLADA'`},
{g:1,b:c=>`Saca las evidencias recogidas exactamente el dia del hecho, ${c.fecha}.`,
 h:"fecha_recogida = '<fecha>'",o:"Lo que se levanto en caliente, antes de que la escena se perdiera.",
 s:c=>`SELECT * FROM evidencias WHERE caso_id = ${c.id} AND fecha_recogida = '${c.fecha}'`},
{g:1,b:c=>`Filtra las llamadas cuyo origen esta identificado, descartando las que figuran como "Sin identificar".`,
 h:"origen <> 'Sin identificar'",o:"Todo lo demas tiene una direccion detras.",
 s:c=>`SELECT * FROM llamadas WHERE caso_id = ${c.id} AND origen <> 'Sin identificar'`},
{g:1,b:c=>`Aisla las llamadas del numero ${c.num} en este expediente.`,
 h:"numero = '<numero>'",o:"El numero que se repite. En este archivo eso nunca es casualidad.",
 s:c=>`SELECT * FROM llamadas WHERE caso_id = ${c.id} AND numero = '${c.num}'`},
{g:1,b:c=>`Quedate con los testigos presenciales del expediente.`,
 h:"tipo = 'PRESENCIAL'",o:"Los que estuvieron alli. El resto son de oidas.",
 s:c=>`SELECT * FROM testigos WHERE caso_id = ${c.id} AND tipo = 'PRESENCIAL'`},
{g:1,b:c=>`En el censo de personas, busca a quienes tienen alias registrado.`,
 h:"IS NOT NULL comprueba que la columna tiene valor.",o:"Cuatro apodos en todo el archivo. Los apodos delatan ambiente.",
 re:"is not null",s:c=>`SELECT * FROM personas WHERE alias IS NOT NULL`},

/* ════ 2 · ORDEN DE DILIGENCIAS ════ */
{g:2,b:c=>`Ordena las llamadas de esa noche por hora, de la primera a la ultima.`,
 h:"ORDER BY hora",o:"La secuencia completa. Asi se lee una noche.",
 re:"order by",s:c=>`SELECT * FROM llamadas WHERE caso_id = ${c.id} ORDER BY hora`},
{g:2,b:c=>`Ordena ahora esas llamadas de la mas larga a la mas corta.`,
 h:"ORDER BY duracion_seg DESC",o:"La conversacion mas larga de la noche encabeza la lista.",
 re:"desc",s:c=>`SELECT * FROM llamadas WHERE caso_id = ${c.id} ORDER BY duracion_seg DESC`},
{g:2,b:c=>`Quedate solo con la llamada mas larga del expediente.`,
 h:"Combina ORDER BY ... DESC con LIMIT 1",o:"Una sola fila, y pesa mas que el resto del registro.",
 re:"limit",s:c=>`SELECT * FROM llamadas WHERE caso_id = ${c.id} ORDER BY duracion_seg DESC LIMIT 1`},
{g:2,b:c=>`Lista las evidencias del caso ordenadas por su codigo de bolsa.`,
 h:"ORDER BY codigo",o:"EV-01, EV-02, EV-03. El orden en que se levantaron.",
 re:"order by",s:c=>`SELECT * FROM evidencias WHERE caso_id = ${c.id} ORDER BY codigo`},
{g:2,b:c=>`Ordena los sospechosos por estado de coartada y, dentro de cada estado, por su identificador.`,
 h:"ORDER BY admite varias columnas separadas por comas.",o:"Agrupados por excusa. Se ve de un vistazo quien se sostiene.",
 re:"order by",s:c=>`SELECT * FROM sospechosos WHERE caso_id = ${c.id} ORDER BY estado_coartada, sospechoso_id`},
{g:2,b:c=>`Trae el testigo mas fiable del expediente.`,
 h:"ORDER BY fiabilidad DESC LIMIT 1",o:"El testigo que habria que volver a llamar manana.",
 re:"limit",s:c=>`SELECT * FROM testigos WHERE caso_id = ${c.id} ORDER BY fiabilidad DESC LIMIT 1`},
{g:2,b:c=>`Ordena las declaraciones del caso de la mas reciente a la mas antigua.`,
 h:"ORDER BY fecha DESC",o:"La ultima vez que alguien hablo de este caso.",
 re:"desc",s:c=>`SELECT * FROM declaraciones WHERE caso_id = ${c.id} ORDER BY fecha DESC`},
{g:2,b:c=>`Trae el informe mas reciente firmado sobre ${c.cod}.`,
 h:"ORDER BY fecha DESC LIMIT 1",o:"El ultimo que puso algo por escrito, y cuando.",
 re:"limit",s:c=>`SELECT * FROM informes WHERE caso_id = ${c.id} ORDER BY fecha DESC LIMIT 1`},
{g:2,b:c=>`Sal un momento de este expediente: ordena los siete casos del archivo por ano.`,
 h:"ORDER BY anio sobre la tabla casos.",o:"Cincuenta anos de archivo en siete lineas.",
 re:"order by",s:c=>`SELECT * FROM casos ORDER BY anio`},
{g:2,b:c=>`Del listado de casos ordenado por ano, salta los dos primeros y trae los dos siguientes.`,
 h:"OFFSET salta filas y LIMIT corta: LIMIT 2 OFFSET 2",o:"Paginar un archivo es lo que hace un sistema de verdad.",
 re:"offset",s:c=>`SELECT codigo, titulo, anio FROM casos ORDER BY anio LIMIT 2 OFFSET 2`},
{g:2,b:c=>`Ordena las llamadas del caso primero por sentido y despues por hora.`,
 h:"ORDER BY sentido, hora",o:"Entrantes y salientes, cada bloque en su propia secuencia.",
 re:"order by",s:c=>`SELECT * FROM llamadas WHERE caso_id = ${c.id} ORDER BY sentido, hora`},
{g:2,b:c=>`Trae los cinco primeros nombres del censo de personas en orden alfabetico.`,
 h:"ORDER BY nombre LIMIT 5",o:"El censo completo del archivo empieza aqui.",
 re:"limit",s:c=>`SELECT * FROM personas ORDER BY nombre LIMIT 5`},

/* ════ 3 · CRUCE DE EXPEDIENTES ════ */
{g:3,b:c=>`Los sospechosos solo guardan un identificador de persona. Cruza sospechosos con personas y muestra el nombre junto al estado de su coartada.`,
 h:"JOIN personas p ON p.persona_id = s.persona_id",o:"Por fin tienen nombre. Un identificador no se interroga.",
 re:"join",s:c=>`SELECT p.nombre, s.estado_coartada FROM sospechosos s JOIN personas p ON p.persona_id = s.persona_id WHERE s.caso_id = ${c.id}`},
{g:3,b:c=>`Haz lo mismo con los testigos: nombre y fiabilidad.`,
 h:"Cruza testigos con personas por persona_id.",o:"Nombres y fiabilidad juntos. Ya se puede decidir a quien llamar.",
 re:"join",s:c=>`SELECT p.nombre, t.fiabilidad FROM testigos t JOIN personas p ON p.persona_id = t.persona_id WHERE t.caso_id = ${c.id}`},
{g:3,b:c=>`Cruza declaraciones con personas y muestra quien declaro, que dijo y si firmo.`,
 h:"JOIN personas ON persona_id, y selecciona nombre, contenido y firmada.",
 o:"Las palabras y la firma, una al lado de la otra.",
 re:"join",s:c=>`SELECT p.nombre, d.contenido, d.firmada FROM declaraciones d JOIN personas p ON p.persona_id = d.persona_id WHERE d.caso_id = ${c.id}`},
{g:3,b:c=>`Averigua que forense firmo la autopsia de ${c.vict}, cruzando victimas con personas.`,
 h:"La columna forense_id apunta a personas.persona_id",o:"Un nombre al pie de la autopsia. Alguien a quien aun se puede preguntar.",
 re:"join",s:c=>`SELECT v.nombre, p.nombre AS forense FROM victimas v JOIN personas p ON p.persona_id = v.forense_id WHERE v.caso_id = ${c.id}`},
{g:3,b:c=>`Muestra el codigo y el titulo del expediente junto al nombre del detective que lo instruyo.`,
 h:"JOIN detectives ON detective_id",o:"Cada caso frio tiene un apellido detras.",
 re:"join",s:c=>`SELECT c.codigo, c.titulo, d.nombre FROM casos c JOIN detectives d ON d.detective_id = c.detective_id WHERE c.caso_id = ${c.id}`},
{g:3,b:c=>`Cruza las evidencias de este caso con sus analisis de laboratorio.`,
 h:"JOIN analisis a ON a.evidencia_id = e.evidencia_id",o:"Cada bolsa con su peticion. Y algunas peticiones sin respuesta.",
 re:"join",s:c=>`SELECT e.codigo, e.descripcion, a.tipo, a.estado FROM evidencias e JOIN analisis a ON a.evidencia_id = e.evidencia_id WHERE e.caso_id = ${c.id}`},
{g:3,b:c=>`Repitelo con un cruce por la izquierda, para que aparezcan tambien las evidencias que nunca se mandaron al laboratorio.`,
 h:"LEFT JOIN conserva las filas de la izquierda aunque no haya pareja.",
 o:"Lo que no tiene analisis es tan revelador como lo que si.",
 re:"left join",s:c=>`SELECT e.codigo, a.estado FROM evidencias e LEFT JOIN analisis a ON a.evidencia_id = e.evidencia_id WHERE e.caso_id = ${c.id}`},
{g:3,b:c=>`Encadena tres tablas: evidencias, analisis y laboratorios, para saber que laboratorio tiene cada pieza de ${c.cod}.`,
 h:"Dos JOIN seguidos, cada uno con su ON.",o:"Ya sabes a que puerta llamar para cada bolsa.",
 re:"join",s:c=>`SELECT e.codigo, a.tipo, l.nombre FROM evidencias e JOIN analisis a ON a.evidencia_id = e.evidencia_id JOIN laboratorios l ON l.laboratorio_id = a.laboratorio_id WHERE e.caso_id = ${c.id}`},
{g:3,b:c=>`Cruza evidencias con la cadena de custodia y muestra que pieza se movio, cuando y a donde.`,
 h:"JOIN custodia ON evidencia_id",o:"Cada traslado firmado. Y uno de ellos acaba en PURGA.",
 re:"join",s:c=>`SELECT e.codigo, m.fecha, m.desde, m.hasta FROM evidencias e JOIN custodia m ON m.evidencia_id = e.evidencia_id WHERE e.caso_id = ${c.id}`},
{g:3,b:c=>`Une el caso con su victima en una sola fila: codigo, titulo y nombre de la victima.`,
 h:"JOIN victimas ON caso_id",o:"El expediente y la persona, por fin en la misma linea.",
 re:"join",s:c=>`SELECT c.codigo, c.titulo, v.nombre FROM casos c JOIN victimas v ON v.caso_id = c.caso_id WHERE c.caso_id = ${c.id}`},
{g:3,b:c=>`Lista los sospechosos del caso con su nombre, ordenados alfabeticamente.`,
 h:"Cruza con personas y anade ORDER BY p.nombre",o:"La lista de nombres que iria en la portada del informe.",
 re:"join",s:c=>`SELECT p.nombre, s.estado_coartada FROM sospechosos s JOIN personas p ON p.persona_id = s.persona_id WHERE s.caso_id = ${c.id} ORDER BY p.nombre`},
{g:3,b:c=>`Cruza los accesos al sistema con los casos y mira quien ha entrado en ${c.cod}.`,
 h:"JOIN casos ON caso_id, filtrando por el expediente.",o:"Cada consulta deja rastro. Algunas no deberian existir.",
 re:"join",s:c=>`SELECT a.usuario, a.fecha, a.accion FROM accesos a JOIN casos c ON c.caso_id = a.caso_id WHERE c.caso_id = ${c.id}`},
{g:3,b:c=>`Muestra los informes del expediente junto al nombre y la placa de quien los firmo.`,
 h:"JOIN detectives ON detective_id",o:"Firma, placa y fecha. Asi se audita una instruccion.",
 re:"join",s:c=>`SELECT i.fecha, i.tipo, d.nombre, d.placa FROM informes i JOIN detectives d ON d.detective_id = i.detective_id WHERE i.caso_id = ${c.id}`},
{g:3,b:c=>`Cruza las solicitudes de reapertura con el caso y mira si la fiscalia aprobo la de este expediente.`,
 h:"JOIN casos ON caso_id",o:"Aprobada o no, alguien lo intento. Eso ya es algo.",
 re:"join",s:c=>`SELECT c.codigo, r.fecha, r.motivo, r.aprobada FROM reaperturas r JOIN casos c ON c.caso_id = r.caso_id WHERE c.caso_id = ${c.id}`},
{g:3,b:c=>`Muestra el codigo del caso junto a cada numero de telefono registrado esa noche.`,
 h:"JOIN casos ON caso_id desde la tabla llamadas.",o:"Telefonos etiquetados con su expediente. Listos para cruzar con otros.",
 re:"join",s:c=>`SELECT c.codigo, l.numero, l.hora FROM llamadas l JOIN casos c ON c.caso_id = l.caso_id WHERE l.caso_id = ${c.id}`},
{g:3,b:c=>`Comprueba en que expedientes del archivo aparece ${c.sosp} como sospechoso, cruzando personas, sospechosos y casos.`,
 h:"Tres tablas unidas y un filtro por p.nombre.",o:"Si sale en mas de una fila, el archivo lleva anos escondiendo una coincidencia.",
 re:"join",s:c=>`SELECT p.nombre, ca.codigo, s.estado_coartada FROM personas p JOIN sospechosos s ON s.persona_id = p.persona_id JOIN casos ca ON ca.caso_id = s.caso_id WHERE p.nombre = '${c.sosp}'`},

/* ════ 4 · RECUENTO FORENSE ════ */
{g:4,b:c=>`Cuenta cuantos sospechosos tiene registrados ${c.cod}.`,
 h:"COUNT(*) devuelve el numero de filas.",o:"Una cifra que cabe en una frase del informe.",
 re:"count",s:c=>`SELECT COUNT(*) FROM sospechosos WHERE caso_id = ${c.id}`},
{g:4,b:c=>`Cuenta las evidencias recogidas en este expediente.`,h:"COUNT(*) sobre evidencias.",
 o:"Tres bolsas. Cincuenta anos. Ninguna respuesta.",
 re:"count",s:c=>`SELECT COUNT(*) FROM evidencias WHERE caso_id = ${c.id}`},
{g:4,b:c=>`Cuenta las llamadas registradas la noche del hecho.`,h:"COUNT(*) sobre llamadas.",
 o:"El volumen exacto de trafico telefonico de esa noche.",
 re:"count",s:c=>`SELECT COUNT(*) FROM llamadas WHERE caso_id = ${c.id}`},
{g:4,b:c=>`Suma los segundos de todas las llamadas del expediente.`,
 h:"SUM(duracion_seg)",o:"Minutos de conversacion que nadie escucho nunca.",
 re:"sum",s:c=>`SELECT SUM(duracion_seg) FROM llamadas WHERE caso_id = ${c.id}`},
{g:4,b:c=>`Calcula la duracion media de esas llamadas, redondeada a un decimal.`,
 h:"ROUND(AVG(duracion_seg), 1)",o:"La media esconde a las dos llamadas que se salen de ella.",
 re:"avg",s:c=>`SELECT ROUND(AVG(duracion_seg), 1) FROM llamadas WHERE caso_id = ${c.id}`},
{g:4,b:c=>`Averigua la hora de la primera y de la ultima llamada de la noche.`,
 h:"MIN(hora) y MAX(hora) en la misma consulta.",o:"La ventana temporal completa, de extremo a extremo.",
 re:"min",s:c=>`SELECT MIN(hora), MAX(hora) FROM llamadas WHERE caso_id = ${c.id}`},
{g:4,b:c=>`Averigua la fiabilidad maxima entre los testigos del caso.`,
 h:"MAX(fiabilidad)",o:"El techo de credibilidad del que dispone este expediente.",
 re:"max",s:c=>`SELECT MAX(fiabilidad) FROM testigos WHERE caso_id = ${c.id}`},
{g:4,b:c=>`Cuenta cuantas llamadas hubo de cada sentido, agrupando por sentido.`,
 h:"GROUP BY sentido junto a COUNT(*)",o:"Entrantes frente a salientes. El desequilibrio dice mucho.",
 re:"group by",s:c=>`SELECT sentido, COUNT(*) FROM llamadas WHERE caso_id = ${c.id} GROUP BY sentido`},
{g:4,b:c=>`Cuenta cuantos sospechosos hay por cada estado de coartada.`,
 h:"GROUP BY estado_coartada",o:"El reparto de excusas del expediente, en cifras.",
 re:"group by",s:c=>`SELECT estado_coartada, COUNT(*) FROM sospechosos WHERE caso_id = ${c.id} GROUP BY estado_coartada`},
{g:4,b:c=>`Cuenta las evidencias del caso agrupadas por su estado en deposito.`,
 h:"GROUP BY estado sobre evidencias.",o:"Lo sellado, lo degradado y lo que ya no esta.",
 re:"group by",s:c=>`SELECT estado, COUNT(*) FROM evidencias WHERE caso_id = ${c.id} GROUP BY estado`},
{g:4,b:c=>`Cuenta los testigos del expediente agrupados por tipo.`,
 h:"GROUP BY tipo sobre testigos.",o:"Presenciales, de referencia y algun anonimo suelto.",
 re:"group by",s:c=>`SELECT tipo, COUNT(*) FROM testigos WHERE caso_id = ${c.id} GROUP BY tipo`},
{g:4,b:c=>`Cuenta cuantos numeros de telefono distintos aparecen esa noche.`,
 h:"COUNT(DISTINCT numero)",o:"Pocas lineas, muchas llamadas. Alguien insistia.",
 re:"distinct",s:c=>`SELECT COUNT(DISTINCT numero) FROM llamadas WHERE caso_id = ${c.id}`},
{g:4,b:c=>`En todo el archivo, averigua que casos tienen mas de tres sospechosos registrados.`,
 h:"GROUP BY caso_id con HAVING COUNT(*) > 3",o:"Los expedientes con mas nombres no son los mas cerca de resolverse.",
 re:"having",s:c=>`SELECT caso_id, COUNT(*) FROM sospechosos GROUP BY caso_id HAVING COUNT(*) > 3`},
{g:4,b:c=>`Cuenta cuantos analisis hay en cada estado en todo el laboratorio.`,
 h:"GROUP BY estado sobre la tabla analisis, sin filtrar por caso.",
 o:"El atasco del laboratorio, medido por primera vez.",
 re:"group by",s:c=>`SELECT estado, COUNT(*) FROM analisis GROUP BY estado`},
{g:4,b:c=>`Cuenta cuantas evidencias tiene cada caso del archivo, mostrando el codigo del expediente.`,
 h:"JOIN casos con evidencias y agrupa por codigo.",o:"Siete expedientes, tres bolsas cada uno. Simetria de archivo, no de investigacion.",
 re:"group by",s:c=>`SELECT c.codigo, COUNT(e.evidencia_id) FROM casos c JOIN evidencias e ON e.caso_id = c.caso_id GROUP BY c.codigo ORDER BY c.codigo`},
{g:4,b:c=>`Busca en todo el archivo los numeros de telefono que aparecen en mas de una llamada.`,
 h:"GROUP BY numero con HAVING COUNT(*) > 1",o:"Un numero repetido entre dos expedientes distintos. Eso ya no es ruido.",
 re:"having",s:c=>`SELECT numero, COUNT(*) FROM llamadas GROUP BY numero HAVING COUNT(*) > 1 ORDER BY numero`},

/* ════ 5 · INTERROGATORIO PROFUNDO ════ */
{g:5,b:c=>`Trae del censo las fichas completas de las personas investigadas en ${c.cod}, usando una subconsulta.`,
 h:"WHERE persona_id IN (SELECT persona_id FROM sospechosos WHERE caso_id = <id>)",
 o:"El censo completo de los sospechosos, con su estado de localizacion.",
 re:"select[\\s\\S]*select",s:c=>`SELECT * FROM personas WHERE persona_id IN (SELECT persona_id FROM sospechosos WHERE caso_id = ${c.id})`},
{g:5,b:c=>`Lista las evidencias de este caso que tienen algun analisis pendiente, preguntando primero al laboratorio.`,
 h:"WHERE evidencia_id IN (SELECT evidencia_id FROM analisis WHERE estado = 'PENDIENTE')",
 o:"Lo que se puede desbloquear manana con una sola firma.",
 re:"select[\\s\\S]*select",s:c=>`SELECT * FROM evidencias WHERE caso_id = ${c.id} AND evidencia_id IN (SELECT evidencia_id FROM analisis WHERE estado = 'PENDIENTE')`},
{g:5,b:c=>`Ahora al reves: las evidencias del caso que NO tienen ningun analisis pendiente.`,
 h:"NOT IN invierte la pertenencia.",o:"Lo que ya no da mas de si, al menos con la tecnologia de entonces.",
 re:"not in",s:c=>`SELECT * FROM evidencias WHERE caso_id = ${c.id} AND evidencia_id NOT IN (SELECT evidencia_id FROM analisis WHERE estado = 'PENDIENTE')`},
{g:5,b:c=>`En todo el archivo, lista los casos en los que existe al menos un sospechoso que nunca declaro.`,
 h:"EXISTS con una subconsulta correlacionada por caso_id.",
 o:"Casi todos. Un archivo entero construido sobre gente que no hablo.",
 re:"exists",s:c=>`SELECT * FROM casos c WHERE EXISTS (SELECT 1 FROM sospechosos s WHERE s.caso_id = c.caso_id AND s.estado_coartada = 'SIN DECLARAR')`},
{g:5,b:c=>`Busca las personas del censo que no han prestado ninguna declaracion en todo el archivo.`,
 h:"NOT EXISTS con una subconsulta correlacionada por persona_id.",
 o:"Nombres que figuran en el expediente y de los que no existe una sola palabra firmada.",
 re:"not exists",s:c=>`SELECT * FROM personas p WHERE NOT EXISTS (SELECT 1 FROM declaraciones d WHERE d.persona_id = p.persona_id)`},
{g:5,b:c=>`Muestra el nombre de la victima junto al numero de sospechosos del caso, calculado con una subconsulta en la lista de columnas.`,
 h:"SELECT v.nombre, (SELECT COUNT(*) FROM sospechosos s WHERE s.caso_id = v.caso_id) FROM victimas v ...",
 o:"Una victima, varios sospechosos, ninguna condena.",
 re:"select[\\s\\S]*select",s:c=>`SELECT v.nombre, (SELECT COUNT(*) FROM sospechosos s WHERE s.caso_id = v.caso_id) AS n_sospechosos FROM victimas v WHERE v.caso_id = ${c.id}`},
{g:5,b:c=>`Saca las llamadas de este expediente que duraron mas que la media de esa misma noche.`,
 h:"Compara duracion_seg con (SELECT AVG(duracion_seg) FROM llamadas WHERE caso_id = <id>)",
 o:"Las llamadas que se salen de la media son las que hay que escuchar.",
 re:"select[\\s\\S]*select",s:c=>`SELECT * FROM llamadas WHERE caso_id = ${c.id} AND duracion_seg > (SELECT AVG(duracion_seg) FROM llamadas WHERE caso_id = ${c.id})`},
{g:5,b:c=>`Monta una consulta con nombre propio: define un bloque WITH llamado pendientes con los analisis sin resultado y luego consultalo.`,
 h:"WITH pendientes AS (SELECT ...) SELECT * FROM pendientes",
 o:"Una consulta con partes tiene nombre y se lee. Eso es un informe, no un apano.",
 re:"with",s:c=>`WITH pendientes AS (SELECT * FROM analisis WHERE estado = 'PENDIENTE') SELECT * FROM pendientes`},
{g:5,b:c=>`Amplia el bloque anterior: cruza esos analisis pendientes con las evidencias de ${c.cod}.`,
 h:"WITH pendientes AS (...) SELECT ... FROM evidencias e JOIN pendientes p ON ...",
 o:"Lo que este expediente concreto tiene atascado en el laboratorio.",
 re:"with",s:c=>`WITH pendientes AS (SELECT * FROM analisis WHERE estado = 'PENDIENTE') SELECT e.codigo, e.descripcion, p.tipo FROM evidencias e JOIN pendientes p ON p.evidencia_id = e.evidencia_id WHERE e.caso_id = ${c.id}`},
{g:5,b:c=>`Busca en todo el archivo a las personas investigadas como sospechosas en mas de un expediente.`,
 h:"Agrupa sospechosos por persona_id con HAVING COUNT(*) > 1 y usa esa lista en un IN.",
 o:"Ahi esta la grieta del archivo: los mismos nombres en expedientes separados por decadas.",
 re:"having",s:c=>`SELECT * FROM personas WHERE persona_id IN (SELECT persona_id FROM sospechosos GROUP BY persona_id HAVING COUNT(*) > 1)`},
{g:5,b:c=>`Averigua en que expedientes figura ${c.sosp}, usando una subconsulta sobre el censo.`,
 h:"WHERE persona_id = (SELECT persona_id FROM personas WHERE nombre = '<nombre>')",
 o:"Un nombre, y detras de el todos los casos que lo mencionan.",
 re:"select[\\s\\S]*select",s:c=>`SELECT * FROM sospechosos WHERE persona_id = (SELECT persona_id FROM personas WHERE nombre = '${c.sosp}')`},
{g:5,b:c=>`Trata una consulta como si fuera una tabla: cuenta las llamadas largas de este caso a partir de una subconsulta en el FROM.`,
 h:"SELECT COUNT(*) FROM (SELECT ... WHERE duracion_seg > 100) t",
 o:"Una consulta dentro de otra. El archivo ya no te esconde nada.",
 re:"from\\s*\\(",s:c=>`SELECT COUNT(*) FROM (SELECT * FROM llamadas WHERE caso_id = ${c.id} AND duracion_seg > 100) t`},
{g:5,b:c=>`Lista las evidencias de ${c.cod} que tienen al menos un movimiento de custodia registrado.`,
 h:"EXISTS correlacionado contra la tabla custodia.",o:"Lo que se movio deja rastro. Lo que no se movio, tambien.",
 re:"exists",s:c=>`SELECT * FROM evidencias e WHERE e.caso_id = ${c.id} AND EXISTS (SELECT 1 FROM custodia m WHERE m.evidencia_id = e.evidencia_id)`},
{g:5,b:c=>`Trae la llamada mas larga del expediente comparando contra el maximo calculado en una subconsulta.`,
 h:"WHERE duracion_seg = (SELECT MAX(duracion_seg) FROM llamadas WHERE caso_id = <id>)",
 o:"El mismo resultado que con ORDER BY, pero esta vez el sistema calcula el extremo por ti.",
 re:"max",s:c=>`SELECT * FROM llamadas WHERE caso_id = ${c.id} AND duracion_seg = (SELECT MAX(duracion_seg) FROM llamadas WHERE caso_id = ${c.id})`},

/* ════ 6 · RECONSTRUCCION DEL CASO ════ */
{g:6,b:c=>`Traduce la fiabilidad de los testigos a palabras: 5 o mas es SOLIDO, 3 o 4 es DUDOSO y por debajo DESCARTABLE.`,
 h:"CASE WHEN fiabilidad >= 5 THEN 'SOLIDO' WHEN fiabilidad >= 3 THEN 'DUDOSO' ELSE 'DESCARTABLE' END",
 o:"Las cifras no se leen en una reunion. Las etiquetas si.",
 re:"case",s:c=>`SELECT testigo_id, fiabilidad, CASE WHEN fiabilidad >= 5 THEN 'SOLIDO' WHEN fiabilidad >= 3 THEN 'DUDOSO' ELSE 'DESCARTABLE' END AS valoracion FROM testigos WHERE caso_id = ${c.id}`},
{g:6,b:c=>`Clasifica a los sospechosos del caso: si su coartada esta CONFIRMADA marca FUERA, en cualquier otro caso marca VIVO.`,
 h:"CASE WHEN estado_coartada = 'CONFIRMADA' THEN 'FUERA' ELSE 'VIVO' END",
 o:"La lista corta del expediente, en una sola columna.",
 re:"case",s:c=>`SELECT sospechoso_id, estado_coartada, CASE WHEN estado_coartada = 'CONFIRMADA' THEN 'FUERA' ELSE 'VIVO' END AS situacion FROM sospechosos WHERE caso_id = ${c.id}`},
{g:6,b:c=>`En los analisis del archivo, sustituye los resultados vacios por el texto SIN RESULTADO.`,
 h:"COALESCE(resultado, 'SIN RESULTADO')",o:"Un hueco en una tabla es una pregunta sin responder. Ahora se lee como tal.",
 re:"coalesce",s:c=>`SELECT analisis_id, tipo, COALESCE(resultado, 'SIN RESULTADO') AS resultado FROM analisis`},
{g:6,b:c=>`En el censo de personas, muestra el alias y, cuando no exista, el texto SIN ALIAS.`,
 h:"COALESCE(alias, 'SIN ALIAS')",o:"Cuatro apodos y treinta y un silencios.",
 re:"coalesce",s:c=>`SELECT nombre, COALESCE(alias, 'SIN ALIAS') AS alias FROM personas`},
{g:6,b:c=>`Construye una sola columna con el nombre de los sospechosos de este caso seguido de su ocupacion entre parentesis.`,
 h:"Concatena con || : p.nombre || ' (' || p.ocupacion || ')'",
 o:"Una linea por sospechoso, lista para el acta.",
 re:"\\|\\|",s:c=>`SELECT p.nombre || ' (' || p.ocupacion || ')' AS ficha FROM sospechosos s JOIN personas p ON p.persona_id = s.persona_id WHERE s.caso_id = ${c.id}`},
{g:6,b:c=>`Muestra en mayusculas el titulo del expediente y la longitud de ese titulo.`,
 h:"UPPER(titulo) y LENGTH(titulo)",o:"Detalles de formato. Un informe tambien se juzga por como entra por los ojos.",
 re:"upper",s:c=>`SELECT UPPER(titulo) AS titulo, LENGTH(titulo) AS largo FROM casos WHERE caso_id = ${c.id}`},
{g:6,b:c=>`Extrae solo el ano de la fecha de recogida de cada evidencia de ${c.cod}.`,
 h:"EXTRACT(YEAR FROM fecha_recogida)",o:"El ano suelto permite comparar expedientes separados por decadas.",
 re:"extract",s:c=>`SELECT codigo, EXTRACT(YEAR FROM fecha_recogida) AS anio FROM evidencias WHERE caso_id = ${c.id}`},
{g:6,b:c=>`Monta una lista unica con los nombres de los sospechosos y de los testigos de este expediente.`,
 h:"Dos SELECT unidos por UNION; cada uno cruza con personas.",
 o:"Todo el que paso por el expediente, en una sola columna.",
 re:"union",s:c=>`SELECT p.nombre FROM sospechosos s JOIN personas p ON p.persona_id = s.persona_id WHERE s.caso_id = ${c.id} UNION SELECT p.nombre FROM testigos t JOIN personas p ON p.persona_id = t.persona_id WHERE t.caso_id = ${c.id}`},
{g:6,b:c=>`Agrupa las llamadas de la noche en LARGA si pasan de 100 segundos y CORTA si no, y cuenta cuantas hay de cada tipo.`,
 h:"Agrupa por la misma expresion CASE que pones en el SELECT.",
 o:"Dos bloques. Y el bloque corto es el que cuadra con la hora de la muerte.",
 re:"case",s:c=>`SELECT CASE WHEN duracion_seg > 100 THEN 'LARGA' ELSE 'CORTA' END AS tipo, COUNT(*) FROM llamadas WHERE caso_id = ${c.id} GROUP BY CASE WHEN duracion_seg > 100 THEN 'LARGA' ELSE 'CORTA' END`},
{g:6,b:c=>`Corta los diez primeros caracteres del contenido de cada declaracion del expediente.`,
 h:"SUBSTRING(contenido, 1, 10)",o:"Un indice de declaraciones que cabe en media pantalla.",
 re:"substring",s:c=>`SELECT declaracion_id, SUBSTRING(contenido, 1, 10) AS inicio FROM declaraciones WHERE caso_id = ${c.id}`},
{g:6,b:c=>`Calcula, para cada caso del archivo, la duracion media de sus llamadas redondeada a entero.`,
 h:"GROUP BY caso_id con ROUND(AVG(duracion_seg))",o:"Siete medias. La de este expediente no se parece a ninguna otra.",
 re:"round",s:c=>`SELECT caso_id, ROUND(AVG(duracion_seg)) AS media FROM llamadas GROUP BY caso_id ORDER BY caso_id`},
{g:6,b:c=>`Une en un solo listado, sin eliminar repetidos, el codigo de todas las evidencias y el tipo de todos los analisis de este caso.`,
 h:"UNION ALL conserva las filas repetidas.",o:"Inventario y peticiones juntos. El estado real del expediente.",
 re:"union all",s:c=>`SELECT codigo AS dato FROM evidencias WHERE caso_id = ${c.id} UNION ALL SELECT a.tipo FROM analisis a JOIN evidencias e ON e.evidencia_id = a.evidencia_id WHERE e.caso_id = ${c.id}`},
{g:6,b:c=>`Monta el cuadro de mando del expediente: codigo, titulo, nombre de la victima y nombre del detective, en una sola fila.`,
 h:"Dos JOIN desde casos: victimas y detectives.",o:"Una fila que resume cincuenta anos de carpeta.",
 re:"join",s:c=>`SELECT c.codigo, c.titulo, v.nombre AS victima, d.nombre AS detective FROM casos c JOIN victimas v ON v.caso_id = c.caso_id JOIN detectives d ON d.detective_id = c.detective_id WHERE c.caso_id = ${c.id}`},
{g:6,b:c=>`Firma el acta de ${c.cod}: con un bloque WITH que reuna sus analisis pendientes, muestra el codigo del caso, cuantos quedan y la etiqueta REABRIR si hay alguno o ARCHIVAR si no queda ninguno.`,
 h:"WITH p AS (...) SELECT ..., COUNT(...), CASE WHEN COUNT(...) > 0 THEN 'REABRIR' ELSE 'ARCHIVAR' END ...",
 o:"EXPEDIENTE FIRMADO. La maquina acaba de recomendar reabrir un caso que llevaba decadas cerrado en la practica.",
 re:"with",s:c=>`WITH p AS (SELECT a.* FROM analisis a JOIN evidencias e ON e.evidencia_id = a.evidencia_id WHERE e.caso_id = ${c.id} AND a.estado = 'PENDIENTE') SELECT '${c.cod}' AS caso, COUNT(*) AS pendientes, CASE WHEN COUNT(*) > 0 THEN 'REABRIR' ELSE 'ARCHIVAR' END AS decision FROM p`}
];

function EXTRA_pal(c){return c.pal;}

/* ─────────── Construccion de las 714 diligencias ─────────── */
CDB.buildRetos=function(){
  var casos=CDB.TABLES.casos.rows,victimas=CDB.TABLES.victimas.rows;
  var ctxs=casos.map(function(r){
    var v=victimas.filter(function(x){return x[1]===r[0];})[0];
    var ex=EXTRA[r[0]];
    return {id:r[0],cod:r[1],titulo:r[2],anio:r[3],fecha:r[4],distrito:r[5],
            vict:v[2],vedad:v[3],causa:v[8],hini:v[6],hfin:v[7],
            sosp:ex.sosp,tes:ex.tes,ev:ex.ev,num:ex.num,lab:ex.lab,pal:ex.pal,dep:ex.dep,amb:ex.amb};
  });
  var out=[];
  ctxs.forEach(function(c,ci){
    TPL.forEach(function(t,ti){
      out.push({
        caso:ci, g:t.g, tpl:ti,
        b:typeof t.b==="function"?t.b(c):t.b,
        h:t.h,
        o:typeof t.o==="function"?t.o(c):t.o,
        sql:t.s(c),
        re:t.re||null
      });
    });
  });
  CDB.CTX=ctxs;
  return out;
};
CDB.NUM_TPL=TPL.length;

})();

/* ═══════════════════════════════════════════════════════════════
   Lo que cada expediente confiesa cuando se termina de interrogar.
   Son las lineas que el capitan lee en voz alta al cerrar el caso.
   ═══════════════════════════════════════════════════════════════ */
CDB.RESUELTO={
"74-0098":[
" · G. Petrakis es el unico sospechoso con la coartada sin verificar",
"   y el unico que admite el silbido que oyo el guarda forestal.",
" · El silbato EV-01 lleva desde 1974 esperando huellas latentes:",
"   la peticion sigue PENDIENTE en LAB-1, nunca se cancelo.",
" · D. Hollis declaro como presencial con fiabilidad 5 y nadie",
"   volvio a llamarle en veintidos anos."],
"81-0455":[
" · H. Brummel cobraba una deuda a la victima y su coartada nunca",
"   pudo verificarse; P. Sandoval, en cambio, queda fuera.",
" · El pagare EV-02 sigue PENDIENTE de grafologia desde 1981,",
"   con una firma que hoy si se puede cotejar.",
" · R. Kessler, taxista, jamas comparecio. Su nombre reaparece",
"   seis anos despues en el expediente de Echo Park."],
"87-4412":[
" · El peritaje del reloj EV-01 dice que la hora se forzo a mano:",
"   las 03:55 son un decorado, no la hora de la muerte.",
" · El numero 213-555-0392 entra a las 02:10 y vuelve a aparecer,",
"   dieciseis anos despues, la noche del muelle 9.",
" · R. Kessler figura otra vez como sospechoso sin declarar.",
" · El documento de la fuente anonima se oculto en 2009 desde",
"   dentro del propio archivo."],
"94-0770":[
" · La fibra azul EV-01 es compatible con un uniforme de seguridad",
"   y su analisis sigue PENDIENTE desde 1994.",
" · E. Thorne hacia el turno de noche sin supervisor y su coartada",
"   no es verificable. Diecisiete anos despues vuelve a ser el",
"   vigilante de la nave que ardio en Verdugo.",
" · La cinta de audio EV-03 se retiro en la purga de 1996 con una",
"   autorizacion ilegible."],
"99-2310":[
" · La toxicologia es tajante: la dosis de sedante no se la pudo",
"   administrar ella misma.",
" · El libro de firmas registra una salida menos de las personas",
"   que estuvieron en el estudio esa noche.",
" · J. Farrow fue el ultimo en salir y su coartada no se verifico.",
" · La cinta DAT sigue sin leerse: catorce segundos con una voz",
"   que nadie identifico nunca."],
"03-1188":[
" · La hoja de fichaje EV-03 esta alterada a mano; la documentoscopia",
"   lo confirmo en 2004 y nadie actuo.",
" · C. Mellado queda desmentido por el capataz del muelle.",
" · El 213-555-0392 llama tres veces esa noche. Es el mismo numero",
"   que llamaba a la operadora de Echo Park en 1987.",
" · El ADN parcial EV-02 admite recotejo con tecnologia actual.",
" · Un acceso anonimo de 2009, desde 10.14.0.7, oculto al informante."],
"11-0642":[
" · La alarma se desarmo con la llave maestra 07 cuatro minutos",
"   antes de que saltara el sensor de humo.",
" · El acelerante aparecio junto a la puerta de carga: el fuego",
"   se provoco desde dentro, con llave.",
" · E. Thorne era el vigilante esa noche y su coartada no es",
"   verificable. Es el mismo nombre del expediente de Mulholland."]
};
